### ISSUE TITLE
overleaf打不开

### ISSUE THREAD

**Issue by Airbala** [Jeffrey28/HNU_DoctoralThesis_Latex#1]
大佬，怎么用overleaf编辑这个啊，overleaf编译报错

**Comment by Jeffrey28** [comment]
报错信息让我看一下，如何使用overleaf，是否选用了正确的编译器

**Comment by Airbala** [comment]
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/39217135/236786788-2fcbb90f-c808-465a-8e66-46c2622f2064.png">

**Comment by Airbala** [comment]
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/39217135/236786896-0e380105-0751-4d17-8481-5a4e780da395.png">

**Comment by Airbala** [comment]
<img width="352" alt="截屏2023-05-08 17 19 33" src="https://user-images.githubusercontent.com/39217135/236787043-f32ba3c7-9ea7-404f-8318-e9fda5db0c5a.png">

**Comment by Jeffrey28** [comment]
上图的这一行是为了能够使得中文字体加粗的，如果使用overleaf，先把这一行注释掉看一下

**Comment by Jeffrey28** [comment]
稍等我看错了，我去看一下，overleaf有一段时间没有使用了

**Comment by Airbala** [comment]
overleaf变异时间太长了。  麻烦大佬了

**Comment by Jeffrey28** [comment]
现在可以了，修复上传了SimSun.ttf和SimHei.ttf字体，然后更改cls的第39和40行，为：
\setCJKmainfont{SimSun.ttf}[AutoFakeBold]
\setCJKsansfont{SimHei.ttf}

**Comment by Airbala** [comment]
对了  我突然想到  硕士论文可以用嘛

**Comment by Jeffrey28** [comment]
当然可以，就是修改一下封面内容

**Comment by Airbala** [comment]
好的好的   谢谢大佬  我试一下   我之前的模板有大问题被打回来了

**Comment by Airbala** [comment]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/39217135/236803173-7271989f-beb3-4753-aa03-d1ba2d837989.png">
大佬这个配置会导致实际的上边距的大小小于2.2   这是咋回事啊

**Comment by Jeffrey28** [comment]
误差多大？

**Comment by Airbala** [comment]
大概0.4cm

**Comment by Jeffrey28** [comment]
这个应该不会有啥问题，可以自己斟酌修改一下

**Comment by Airbala** [comment]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/39217135/236804108-0c4bf49f-f894-4853-b584-936102ff2cdb.png">
实际编译出来是这个效果

**Comment by Airbala** [comment]
很明显不到2.2

**Comment by Jeffrey28** [comment]
模板大小应该没有错，你这样看也不是实际大小

**Comment by Airbala** [comment]
模板大小数值上是正确的   但是实际上不说大小   就说左右边距2.5cm  上下边距2.2cm   这个比例在上面的图上就有点不对

**Comment by Jeffrey28** [comment]
很简单，你打印下来看看

**Comment by NotHaozi** [comment]
大佬，学校要求每页35行，每行35字，字体大小是不是也不太对啊

**Comment by Jeffrey28** [comment]
> 大佬，学校要求每页35行，每行35字，字体大小是不是也不太对啊

最新版本就是35行的，已经确认过没错
